sudo: true
language: haskell

git:
  depth: 5

cabal: "2.0"

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:
  - ghc: 8.2.2
  - ghc: 8.4.4
  - ghc: 8.6.3

  - ghc: 8.6.3
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"

install:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal new-update
      cabal new-build --enable-tests --enable-benchmarks
    else
      curl -sSL https://get.haskellstack.org/ | sh
      stack --version
      stack build --system-ghc --test --no-run-tests
    fi

script:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal new-test $ALLOWNEWER
    else
      stack build --system-ghc --test --bench --no-run-benchmarks --no-terminal --ghc-options=-Werror
    fi

notifications:
  email: false
